# Infrastructure-as-code pipeline that deploys a new instance of Azure Machine Learning
trigger:
  branches:
    include:
      - main
  paths:
    include:
      - model_training/.pipelines/arm-templates/*
pr:
  branches:
    include:
      - main
  paths:
    include:
      - model_training/.pipelines/arm-templates/*

pool:
  vmImage: "ubuntu-latest"

variables:
  - template: variable_template.yml
 
steps:
  - task: AzureResourceGroupDeployment@2
    inputs:
      azureSubscription: "$(AZURE_RM_SVC_CONNECTION)"
      action: "Create Or Update Resource Group"
      resourceGroupName: "$(RESOURCE_GROUP)"
      location: $(LOCATION)
      templateLocation: "Linked artifact"
      csmFile: "$(Build.SourcesDirectory)/model_training/.pipelines/arm-templates/cloud-environment.json"
      overrideParameters: "-baseName $(BASE_NAME) -location $(LOCATION) -workspace $(WORKSPACE_NAME) -sku $(WORKSPACE_SKU)"
      deploymentMode: "Incremental"
    displayName: "Deploy Azure Machine Learning Resources"