trigger: none

resources:
  pipelines:
  - pipeline: build
    source: 'CVA - File Mover - BUILD'
  
variables:
  azureSubscription: 'Demo Account'

stages:
- template: azure-release-pipelines-template.yml
  parameters:
    stageName: 'CI'
    environment: 'DEVICE001'