parameters: 
- name: azureSubscription
  default: ''
- name: stageName
  default: ''
- name: environment
  default: ''
- name: acrAddress
  default: ''
- name: acrPassword
  default: ''
- name: acrUser
  default: ''
- name: blobConnectionString
  default: ''
- name: deploymentId
  default: ''
- name: deviceId
  default: ''
- name: iotHubName
  default: ''


stages:
  - stage: ${{ parameters.stageName }}
    displayName: ${{ parameters.stageName }}

    jobs:
    - deployment: Deploy
      displayName: Deploy
      environment: ${{ parameters.environment }}
      pool:
        vmImage: 'ubuntu-latest'
  
      strategy:
        runOnce:
          deploy:
  
            steps:
            - task: Bash@3
              inputs:
                targetType: 'inline'
                script: 'pip install -U iotedgedev'

            - task: AzureCLI@1
              displayName: 'Azure CLI: Get ACR credentials'
              inputs:
                azureSubscription: ${{ parameters.azureSubscription }}
                scriptLocation: inlineScript
                inlineScript: |
                  VAR1="computervisioncracrci.azurecr.io/cvcoe/filemover:"
                  VAR2=$(az acr repository show-tags -n computervisioncracrci --repository cvcoe/filemover --orderby time_asc --query [-2])
                  VAR3=`sed -e 's/^"//' -e 's/"$//' <<<"$VAR2"`
                  VAR4="$VAR1$VAR3"                 
                  echo "##vso[task.setvariable variable=MODULE_FILEMOVER_IMAGE_NAME]${VAR4}"

            - task: Bash@3
              inputs:
                targetType: 'inline'
                script: 'echo  "VARIABLE: $(MODULE_FILEMOVER_IMAGE_NAME)"'

            - task: AzureIoTEdge@2
              displayName: 'Azure IoT Edge - Generate deployment manifest'
              inputs:
                action: 'Generate deployment manifest'
                templateFilePath: '$(Pipeline.Workspace)/build/edge_instances/deployment.template.json'
                deploymentManifestOutputPath: '$(Pipeline.Workspace)/build/edge_instances/configs/deployment.json'
              env:
                ACR_ADDRESS: ${{ parameters.acrAddress }}
                ACR_PASSWORD: ${{ parameters.acrPassword }}
                ACR_USER: ${{ parameters.acrUser }}
                BLOB_LOCAL_CONNSTR: ${{ parameters.blobConnectionString }}
                MODULE_FILEMOVER_VERSION: '$(MODULE_FILEMOVER_IMAGE_NAME)'
            
            - task: PublishPipelineArtifact@1
              inputs:
                targetPath: '$(Pipeline.Workspace)/build/edge_instances/configs'
                artifact: 'configs'
                publishLocation: 'pipeline'

            - task: AzureIoTEdge@2
              displayName: 'Azure IoT Edge - Deploy to IoT Edge devices'
              inputs:
                action: 'Deploy to IoT Edge devices'
                deploymentFilePath: '$(Pipeline.Workspace)/build/edge_instances/configs/deployment.json'
                azureSubscription: ${{ parameters.azureSubscription }}
                iothubname: ${{ parameters.iotHubName }}
                deploymentid: ${{ parameters.deploymentId }}
                deviceOption: 'Single Device'
                deviceId: ${{ parameters.deviceId }}

