parameters: 
- name: stageName
  default: ''
- name: environment
  default: ''
- name: acrAddress
  default: ''
- name: acrPassword
  default: ''
- name: acrUser
  default: ''
- name: blobConnectionString
  default: ''

stages:
  - stage: ${{ parameters.stageName }}
    displayName: ${{ parameters.stageName }}

    jobs:
    - deployment: Deploy
      displayName: Deploy
      environment: ${{ parameters.environment }}
      pool:
        vmImage: 'ubuntu-latest'
  
      strategy:
        runOnce:
          deploy:
  
            steps:
            - task: Bash@3
              inputs:
                targetType: 'inline'
                script: 'pip install -U iotedgedev'

            - task: AzureIoTEdge@2
              displayName: 'Azure IoT Edge - Generate deployment manifest'
              inputs:
                action: 'Generate deployment manifest'
                templateFilePath: '$(Pipeline.Workspace)/build/edge_instances/deployment.template.json'
                deploymentManifestOutputPath: '$(Pipeline.Workspace)/build/edge_instances/configs/deployment.json'
              env:
                ACR_ADDRESS: ${{ parameters.acrAddress }}
                ACR_PASSWORD: ${{ parameters.acrPassword }}
                ACR_USER: ${{ parameters.acrUser }}
                BLOB_LOCAL_CONNSTR: ${{ parameters.blobConnectionString }}

            - task: PublishPipelineArtifact@1
              inputs:
                targetPath: 'edge_instances'
                artifact: 'edge_instances'
                publishLocation: 'pipeline'