trigger: none

resources:
  pipelines:
  - pipeline: build
    source: 'CVA - Device Deployments - BUILD'
  
variables:
  azureSubscription: 'Demo Account'
  acrAddress: 'computervisioncracrci.azurecr.io'
  acrUser: 'computervisioncracrci'
  
stages:
- template: azure-release-pipelines-template.yml
  parameters:
    stageName: 'CI'
    environment: 'DEVICE001'
    azureSubscription: ${{ variables.azureSubscription }}
    acrAddress: ${{ variables.acrAddress }}
    acrPassword: $(acrPassword)
    acrUser: ${{ variables.acrUser }}
    blobConnectionString: $(blobConnectionString)
    deploymentId: '$(System.TeamProject)-DEVICE001-$(Build.BuildNumber)'
    deviceId: 'device001'
    iotHubName: 'computervisioncr-ci'