trigger: none

resources:
  pipelines:
  - pipeline: build
    source: 'CVA - File Mover - BUILD'
  
variables:
  azureSubscription: 'Demo Account'
  acrAddress: 'computervisioncracrci.azurecr.io'
  acrUser: 'computervisioncracrci'
  
stages:
- template: azure-release-pipelines-template.yml
  parameters:
    stageName: 'CI'
    environment: 'DEVICE001'
    acrAddress: ${{ variables.acrAddress }}
    acrPassword: $(acrPassword)
    acrUser: ${{ variables.acrUser }}
    blobConnectionString: $(blobConnectionString)